### ISSUE TITLE
Nonce is invalid!

### ISSUE THREAD

**Issue by Sarah-C** [chillibasket/arduino-classes#1]
Hiyah!

I went to post a comment on your website, and got that error after clicking submit on this page:
https://wired.chillibasket.com/2020/05/servo-trajectory/

It failed on Chrome and Firefox too!

......
I made a quick little visualise in JS for the library: https://codepen.io/SarahC/pen/MWvYVbr?editors=0010

**Comment by chillibasket** [comment]
Hi thanks for pointing that out; there was an error in the comments plugin I use. Updating it to the newest version has now fixed the commenting issue.

That Codepen visualisations looks nice, it is a good way of seeing what the library is actually doing!

**Comment by Sarah-C** [comment]
Any time!

I wanted to visualise how the acc/dec curve changed depending on the top speed/total angle to move, and the two acc/dec speed settings. Your maths is great - there's no sharp plateaus even with fast moves , fast acc/dec and close angles.

xx
